/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.GUI;

import NEGOCIOS.UsuarioDTO;
import NEGOCIOS.UsuarioServicio;
import javax.swing.JOptionPane;

/**
 *
 * @author osval
 */
public class Saldo extends javax.swing.JFrame {

    /**
     * Creates new form Saldo
     */
    private UsuarioDTO usuario;
    private UsuarioServicio usuarioServicio;

    public Saldo(UsuarioDTO usuario) {
        initComponents();
        this.usuario = usuario;
        this.usuarioServicio = new UsuarioServicio();
        mostrarSaldoTxt.setText(String.format("%.2f", usuario.getSaldo()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        montoTxt = new javax.swing.JTextField();
        confirmarMontoTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        añadirBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mostrarSaldoTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Añadir Saldo");

        jLabel2.setText("Monto a añadir");

        jLabel3.setText("Confirmar monto");

        añadirBtn.setText("Confirmar");
        añadirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirBtnActionPerformed(evt);
            }
        });

        atrasBtn.setText("Atras");
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Tu saldo es:");

        mostrarSaldoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSaldoTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(añadirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(atrasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(montoTxt)
                            .addComponent(confirmarMontoTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel4)))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mostrarSaldoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(mostrarSaldoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(montoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmarMontoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(añadirBtn)
                .addGap(39, 39, 39)
                .addComponent(atrasBtn)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void añadirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirBtnActionPerformed
        String monto = montoTxt.getText();
    String confirmarMonto = confirmarMontoTxt.getText();

    // Validar que los montos coincidan
    if (!monto.equals(confirmarMonto)) {
        JOptionPane.showMessageDialog(this, "Los montos no coinciden.");
        return;
    } else {
        try {
            double montoDouble = Double.parseDouble(monto);

            // Asegurarse de que el monto sea positivo
            if (montoDouble <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser positivo.");
                return;
            }

            // Llamar al método de UsuarioServicio para agregar saldo
            boolean exito = usuarioServicio.agregarSaldo(usuario.getSaldo()); // Llamada actualizada

            if (exito) {
                // Actualizar el saldo en el objeto UsuarioDTO
                double nuevoSaldo = usuario.getSaldo() + montoDouble;
                usuario.setSaldo(nuevoSaldo);

                // Mostrar mensaje de éxito
                JOptionPane.showMessageDialog(this, "Saldo añadido correctamente. Nuevo saldo: " + String.format("%.2f", nuevoSaldo));

                // Limpiar los campos de texto
                montoTxt.setText("");
                confirmarMontoTxt.setText("");
                mostrarSaldoTxt.setText(String.format("%.2f", usuario.getSaldo()));
            } else {
                JOptionPane.showMessageDialog(this, "Error al añadir saldo en la base de datos.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto válido.");
        }
    }
    }//GEN-LAST:event_añadirBtnActionPerformed

    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtnActionPerformed
        dispose();
    }//GEN-LAST:event_atrasBtnActionPerformed

    private void mostrarSaldoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSaldoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarSaldoTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBtn;
    private javax.swing.JButton añadirBtn;
    private javax.swing.JTextField confirmarMontoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField montoTxt;
    private javax.swing.JTextField mostrarSaldoTxt;
    // End of variables declaration//GEN-END:variables
}
